In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("../data/raw/Base.csv")

In [3]:
data.describe().round(1).T

,count,mean,std,min,25%,50%,75%,max
fraud_bool,1000000.0,0.0,0.1,0.0,0.0,0.0,0.0,1.0
income,1000000.0,0.6,0.3,0.1,0.3,0.6,0.8,0.9
name_email_similarity,1000000.0,0.5,0.3,0.0,0.2,0.5,0.8,1.0
prev_address_months_count,1000000.0,16.7,44.0,-1.0,-1.0,-1.0,12.0,383.0
current_address_months_count,1000000.0,86.6,88.4,-1.0,19.0,52.0,130.0,428.0
customer_age,1000000.0,33.7,12.0,10.0,20.0,30.0,40.0,90.0
days_since_request,1000000.0,1.0,5.4,0.0,0.0,0.0,0.0,78.5
intended_balcon_amount,1000000.0,8.7,20.2,-15.5,-1.2,-0.8,5.0,113.0
zip_count_4w,1000000.0,1572.7,1005.4,1.0,894.0,1263.0,1944.0,6700.0
velocity_6h,1000000.0,5665.3,3009.4,-170.6,3436.4,5319.8,7680.7,16715.6
velocity_24h,1000000.0,4769.8,1479.2,1300.3,3593.2,4749.9,5752.6,9506.9
velocity_4w,1000000.0,4856.3,919.8,2825.7,4268.4,4913.4,5488.1,6994.8
bank_branch_count_8w,1000000.0,184.4,459.6,0.0,1.0,9.0,25.0,2385.0
date_of_birth_distinct_emails_4w,1000000.0,9.5,5.0,0.0,6.0,9.0,13.0,39.0
credit_risk_score,1000000.0,131.0,69.7,-170.0,83.0,122.0,178.0,389.0
email_is_free,1000000.0,0.5,0.5,0.0,0.0,1.0,1.0,1.0
phone_home_valid,1000000.0,0.4,0.5,0.0,0.0,0.0,1.0,1.0
phone_mobile_valid,1000000.0,0.9,0.3,0.0,1.0,1.0,1.0,1.0
bank_months_count,1000000.0,10.8,12.1,-1.0,-1.0,5.0,25.0,32.0
has_other_cards,1000000.0,0.2,0.4,0.0,0.0,0.0,0.0,1.0
proposed_credit_limit,1000000.0,515.9,487.6,190.0,200.0,200.0,500.0,2100.0
foreign_request,1000000.0,0.0,0.2,0.0,0.0,0.0,0.0,1.0
session_length_in_minutes,1000000.0,7.5,8.0,-1.0,3.1,5.1,8.9,85.9
keep_alive_session,1000000.0,0.6,0.5,0.0,0.0,1.0,1.0,1.0
device_distinct_emails_8w,1000000.0,1.0,0.2,-1.0,1.0,1.0,1.0,2.0
device_fraud_count,1000000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
month,1000000.0,3.3,2.2,0.0,1.0,3.0,5.0,7.0

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 32 columns):
 #   Column                            Non-Null Count    Dtype
---  ------                            --------------    -----
 0   fraud_bool                        1000000 non-null  int64
 1   income                            1000000 non-null  float64
 2   name_email_similarity             1000000 non-null  float64
 3   prev_address_months_count         1000000 non-null  int64
 4   current_address_months_count      1000000 non-null  int64
 5   customer_age                      1000000 non-null  int64
 6   days_since_request                1000000 non-null  float64
 7   intended_balcon_amount            1000000 non-null  float64
 8   payment_type                      1000000 non-null  object
 9   zip_count_4w                      1000000 non-null  int64
 10  velocity_6h                       1000000 non-null  float64
 11  velocity_24h                      1000000 non-null  float64
 12  velocity_4w                       1000000 non-null  float64
 13  bank_branch_count_8w              1000000 non-null  int64
 14  date_of_birth_distinct_emails_4w  1000000 non-null  int64
 15  employment_status                 1000000 non-null  object
 16  credit_risk_score                 1000000 non-null  int64
 17  email_is_free                     1000000 non-null  int64
 18  housing_status                    1000000 non-null  object
 19  phone_home_valid                  1000000 non-null  int64
 20  phone_mobile_valid                1000000 non-null  int64
 21  bank_months_count                 1000000 non-null  int64
 22  has_other_cards                   1000000 non-null  int64
 23  proposed_credit_limit             1000000 non-null  float64
 24  foreign_request                   1000000 non-null  int64
 25  source                            1000000 non-null  object
 26  session_length_in_minutes         1000000 non-null  float64
 27  device_os                         1000000 non-null  object
 28  keep_alive_session                1000000 non-null  int64
 29  device_distinct_emails_8w         1000000 non-null  int64
 30  device_fraud_count                1000000 non-null  int64
 31  month                             1000000 non-null  int64
dtypes: float64(9), int64(18), object(5)
memory usage: 244.1+ MB

In [5]:
data.head().round(2).T

,0,1,2,3,4
fraud_bool,0,0,0,0,0
income,0.3,0.8,0.8,0.6,0.9
name_email_similarity,0.99,0.62,1.0,0.48,0.84
prev_address_months_count,-1,-1,9,11,-1
current_address_months_count,25,89,14,14,29
customer_age,40,20,40,30,40
days_since_request,0.01,0.01,0.01,0.01,5.74
intended_balcon_amount,102.45,-0.85,-1.49,-1.86,47.15
payment_type,AA,AD,AB,AB,AA
zip_count_4w,1059,1658,1095,3483,2339
velocity_6h,13096.04,9223.28,4471.47,14431.99,7601.51
velocity_24h,7850.96,5745.25,5471.99,6755.34,5124.05
velocity_4w,6742.08,5941.66,5992.56,5970.34,5940.73
bank_branch_count_8w,5,3,15,11,1
date_of_birth_distinct_emails_4w,5,18,11,13,6
employment_status,CB,CA,CA,CA,CA
credit_risk_score,163,154,89,90,91
email_is_free,1,1,1,1,0
housing_status,BC,BC,BC,BC,BC
phone_home_valid,0,1,0,0,1
phone_mobile_valid,1,1,1,1,1
bank_months_count,9,2,30,1,26
has_other_cards,0,0,0,0,0
proposed_credit_limit,1500.0,1500.0,200.0,200.0,200.0
foreign_request,0,0,0,0,0
source,INTERNET,INTERNET,INTERNET,INTERNET,INTERNET
session_length_in_minutes,16.22,3.36,22.73,15.22,3.74
device_os,linux,other,windows,linux,other
keep_alive_session,1,1,0,1,0
device_distinct_emails_8w,1,1,1,1,1
device_fraud_count,0,0,0,0,0
month,0,0,0,0,0

In [9]:
data.select_dtypes(object).nunique()

payment_type         5
employment_status    7
housing_status       7
source               2
device_os            5
dtype: int64